### ISSUE TITLE
Vampire the masquerade crash due to nullptr exception

### ISSUE THREAD

**Issue by svelle** [NVIDIAGameWorks/dxvk-remix#9]
When launching vampire the masquerade with the latest master build (dxvk-remix-d7bcdb3-debug) the game crashes as soon as you land in the main menu. you can hear the sound first and then it crashes a couple seconds later.

Error occurs in the `vulkan_presenter.h` at line 212: https://github.com/NVIDIAGameWorks/dxvk-remix/blob/d7bcdb32e8c0eb11bb2b2e7ca6213b15f3432b6d/src/vulkan/vulkan_presenter.h#L212
Looks like it's not properly getting the game window.

Here's the bridge dump from the crash.
[NvRemixBridge.exe_20230427_225605.dmp.zip](https://github.com/NVIDIAGameWorks/dxvk-remix/files/11347910/NvRemixBridge.exe_20230427_225605.dmp.zip)

Call stack:

```
>	d3d9.dll!dxvk::vk::Presenter::isSameHWND(HWND__ * const other) Line 212	C++
 	d3d9.dll!dxvk::D3D9SwapChainEx::Present(const tagRECT * pSourceRect, const tagRECT * pDestRect, HWND__ * hDestWindowOverride, const _RGNDATA * pDirtyRegion, unsigned long dwFlags) Line 395	C++
 	d3d9.dll!dxvk::D3D9DeviceEx::PresentEx(const tagRECT * pSourceRect, const tagRECT * pDestRect, HWND__ * hDestWindowOverride, const _RGNDATA * pDirtyRegion, unsigned long dwFlags) Line 3567	C++
 	d3d9.dll!dxvk::D3D9DeviceEx::Present(const tagRECT * pSourceRect, const tagRECT * pDestRect, HWND__ * hDestWindowOverride, const _RGNDATA * pDirtyRegion) Line 389	C++
 	[External Code]	
```

Launch parameters used for the game (gog release):  
```-game Unofficial_Patch -windowed -dxlevel 70 -novid +mat_disable_d3d9ex 1```

**Comment by AlexDunn** [comment]
Thank you.  Looking at this right now, looks like a recent regression.

**Comment by AlexDunn** [comment]
I have just pushed a fix, give it a minute to percolate and produce a build.  Thanks!

**Comment by AlexDunn** [comment]
Here is the action:  https://github.com/NVIDIAGameWorks/dxvk-remix/actions/runs/4825264556

**Comment by svelle** [comment]
Nice, thanks @AlexDunn It's launching again with the prod release, debug hangs for some reason but at least it isn't crashing anymore. It still doesn't inject in-game but that's not of concern for this gh issue. I'd say this is good to close.

**Comment by AlexDunn** [comment]
Thanks for following up.  Sorry about that. 

Feel free to self-close.  I think we have that set up.
